TekConf/Models/DashboardViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TekConf.Models
{
    public class DashboardViewModel
    {
        public List<Event> events { get; set; }
        public AspNetUsers user { get; set; }
    }
}

TekConf/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using TekConf.Models;
using Microsoft.AspNet.Identity;
using System.Data.Entity;
using System.Web;
using System.IO;

namespace TekConf.Controllers
{
    [Authorize]
    public class DashboardController : Controller
    {
        private teckconfdbEntities db = new teckconfdbEntities();
        // GET: Dashboard
        public ActionResult Index()
        {
            DashboardViewModel dashboardViewModel = new DashboardViewModel();
            string userId = User.Identity.GetUserId<string>();
            List<long> attendee_event_user = db.Event_AspNetUsers.Where(u => u.user_id == userId).Select(u => u.event_id).ToList();
            dashboardViewModel.events = db.Event.Where(e => attendee_event_user.Contains(e.id) && e.time >= DateTime.Today).ToList();

            dashboardViewModel.user = db.AspNetUsers.Where(u => u.Id == userId).FirstOrDefault();
            return View(dashboardViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UpdateProfile([Bind(Include = "Id,Firstname,Lastname,Email,Address")]AspNetUsers user,
            HttpPostedFileBase Picture)
        {
            if (ModelState.IsValid)
            {
                AspNetUsers u = db.AspNetUsers.Find(user.Id);
                u.Firstname = user.Firstname;
                u.Lastname = user.Lastname;
                u.Email = user.Email;
                u.Address = user.Address;
                if (Picture != null)
                {
                    u.Picture = user.Id + Path.GetExtension(Picture.FileName);
                    string downloadFilePath = System.Web.HttpContext.Current.Server.MapPath("/Downloads");
                    string savedFileName = Path.Combine(downloadFilePath, user.Id + Path.GetExtension(Picture.FileName));
                    Picture.SaveAs(savedFileName);
                }

                db.Entry(u).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

TekConf/Controllers/EventsController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using TekConf;
using TekConf.Models;
using Microsoft.AspNet.Identity;

namespace TekConf.Controllers
{
    public class EventsController : Controller
    {
        private teckconfdbEntities db = new teckconfdbEntities();

        // GET: Events
        public ActionResult Index()
        {
            ViewBag.technologies = DataAccess.Technology.GetTechnologiesList();
            return View();
        }

        // POST: Search
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Search(string Near, int? Month, int? Year, long[] technologies, string Topic)
        {
            IQueryable<Event> queryable = db.Event.Where(e => e.time > System.DateTime.Now);
            if (Month != null)
                queryable = queryable.Where(e => e.time.Month == Month);
            if (Year != null)
                queryable = queryable.Where(e => e.time.Year == Year);
            if (!String.IsNullOrEmpty(Topic))
                queryable = queryable.Where(e => e.name.ToLower().Contains(Topic));
            if (technologies != null)
                queryable = queryable.Where(e => technologies.Any(t => e.Technology.Select(et => et.id).Contains(t)));
            var list = queryable.Select(ev => new
            {
                ev.id,
                ev.name,
                ev.time,
                ev.description,
                ev.location
            }).ToList();
            return Content(JsonConvert.SerializeObject(list), "application/json");
        }
        // POST : Events/Details/5 (to participate to an event)
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Participate(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event @event = db.Event.Find(id);
            if (@event == null)
            {
                return HttpNotFound();
            }
            string currentUserId = User.Identity.GetUserId();
            if (currentUserId == null)
            {
                return RedirectToAction("Index");
            }
            Event_AspNetUsers event_AspNetUsers = db.Event_AspNetUsers.Where(u => u.event_id == @event.id && u.user_id == currentUserId).FirstOrDefault();
            if (event_AspNetUsers == null)
            {
                event_AspNetUsers = new Event_AspNetUsers()
                {
                    event_id = @event.id,
                    type = "attendee",
                    user_id = currentUserId
                };
                db.Event_AspNetUsers.Add(event_AspNetUsers);
                db.SaveChanges();
            }
            return RedirectToAction("Details", new { id = id });
        }

        // GET: Events/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event @event = db.Event.Find(id);
            if (@event == null)
            {
                return HttpNotFound();
            }
            string currentUserId = User.Identity.GetUserId();
            ViewBag.IsEventCreator = db.Event_AspNetUsers.Where(u => u.event_id == @event.id && u.user_id == currentUserId && u.type == "speaker" ).FirstOrDefault() != null;

            EventDetailsViewModel eventDetailsViewModel = new EventDetailsViewModel();
            eventDetailsViewModel.Event = @event;
            List<string> speaker_event_user = @event.Event_AspNetUsers.Where(u => u.type == "speaker").Select(u => u.user_id).ToList();
            List<string> attendee_event_user = @event.Event_AspNetUsers.Where(u => u.type == "attendee").Select(u => u.user_id).ToList();

            eventDetailsViewModel.speakers = db.AspNetUsers.Where(u => speaker_event_user.Contains(u.Id)).ToList();
            eventDetailsViewModel.attendees = db.AspNetUsers.Where(u => attendee_event_user.Contains(u.Id)).ToList();

            eventDetailsViewModel.technologies = @event.Technology.ToList();
            Regex youtubeRegex = new Regex(@"youtu(?:\.be|be\.com)/(?:.*v(?:/|=)|(?:.*/)?)([a-zA-Z0-9-_]+)");
            Regex vimeoRegex = new Regex(@"vimeo\.com/(?:.*#|.*/videos/)?([0-9]+)");
            string videoId = "";
            string videoLink = "";
            if (!String.IsNullOrEmpty(@event.video_link))
            {
                Match youtubeMatch = youtubeRegex.Match(@event.video_link);
                Match vimeoMatch = vimeoRegex.Match(@event.video_link);

                if (youtubeMatch.Success)
                {
                    videoId = youtubeMatch.Groups[1].Value;
                    videoLink = "https://www.youtube.com/embed/" + videoId;
                }
                if (vimeoMatch.Success)
                {
                    videoId = vimeoMatch.Groups[1].Value;
                    videoLink = "https://www.player.vimeo.com/video/" + videoId;
                }
            }
            eventDetailsViewModel.googleCalendarLink = "http://www.google.com/calendar/event?action=TEMPLATE&text=" +
                HttpUtility.UrlEncode(@event.name) + "&dates=" + @event.time.ToString("yyyyMMddTHHmmss") + "/" + @event.time.AddHours(1).ToString("yyyyMMddTHHmmss") + "&location=" + HttpUtility.UrlEncode(@event.location) + "&details=" + HttpUtility.UrlEncode(@event.description) + "&sprop=website:tekconf.fr&sprop=name:TekConf";
            ViewBag.videoLink = videoLink;
            return View(eventDetailsViewModel);
        }

        // GET: Events/Create
        [Authorize]
        public ActionResult Create()
        {
            EventCreateViewModel eventCreateViewModel = new EventCreateViewModel();
            eventCreateViewModel.Event = new Event();
            eventCreateViewModel.technologies = DataAccess.Technology.GetTechnologiesList();
            eventCreateViewModel.speakers = DataAccess.AspNetUsers.GetUsersList();
            return View(eventCreateViewModel);
        }

        // POST: Events/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Event @event, long[] technologies, string[] speakers)
        {
            if (technologies == null)
                technologies = new long[] { };
            if (speakers == null)
                speakers = new string[] { };
            if (ModelState.IsValid)
            {
                @event.Technology = db.Technology.Where(t => technologies.Contains(t.id)).ToList();
                db.Event.Add(@event);
                db.SaveChanges();
                @event.Event_AspNetUsers = speakers.Select(s => new Event_AspNetUsers { user_id = s, event_id = @event.id, type = "speaker" }).ToList();
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            EventCreateViewModel eventCreateViewModel = new EventCreateViewModel();
            eventCreateViewModel.Event = @event;
            eventCreateViewModel.technologies = DataAccess.Technology.GetTechnologiesList();
            eventCreateViewModel.speakers = DataAccess.AspNetUsers.GetUsersList();
            return View(eventCreateViewModel);
        }

        // GET: Events/Edit/5
        [Authorize]
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event @event = db.Event.Find(id);
            if (@event == null)
            {
                return HttpNotFound();
            }
            string currentUserId = User.Identity.GetUserId();
            Event_AspNetUsers event_AspNetUsers = db.Event_AspNetUsers.Where(u => u.event_id == @event.id && u.user_id == currentUserId).FirstOrDefault();
            if (event_AspNetUsers == null)
            {
                return RedirectToAction("Index");
            }
            EventEditViewModel eventEditViewModel = new EventEditViewModel();
            eventEditViewModel.Event = @event;
            eventEditViewModel.selectedTechnologies = @event.Technology.ToList();
            eventEditViewModel.technologies = DataAccess.Technology.GetTechnologiesList().Where(t => !@event.Technology.Select(e => e.id).Contains(t.id)).ToList();
            List<string> speaker_event_user = @event.Event_AspNetUsers.Where(u => u.type == "speaker").Select(u => u.user_id).ToList();
            eventEditViewModel.selectedSpeakers = db.AspNetUsers.Where(u => speaker_event_user.Contains(u.Id)).ToList();
            eventEditViewModel.speakers = DataAccess.AspNetUsers.GetUsersList().Where(u => !speaker_event_user.Contains(u.Id)).ToList();
            return View(eventEditViewModel);
        }

        // POST: Events/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Event @event, long[] technologies, string[] speakers)
        {
            if (technologies == null)
                technologies = new long[] { };
            if (speakers == null)
                speakers = new string[] { };

            db.Event.Attach(@event);
            db.Entry(@event).Collection("Technology").Load();
            db.Entry(@event).Collection("Event_AspNetUsers").Load();

TekConf/Views/Dashboard/Index.cshtml
@model TekConf.Models.DashboardViewModel
@{
    ViewBag.Title = "Index";
}

<header class="text-center">
    <h1>Dashboard</h1>
</header>

<div class="container">
    <div class="row">
        <h3>My Events</h3>
        <div class="col-md-6">
            <div class="list-group">
                @foreach (Event e in Model.events)
                {
                    <a href="@Url.Action("Details", "Events", new { id = @e.id })" class="list-group-item">
                        <div class="row">
                            <div class="col-md-9">
                                <h4 class="list-group-item-heading">@e.name <small>@e.time.Date.ToShortDateString() at @e.time.TimeOfDay.ToString("hh':'mm")</small></h4>
                                <p class="list-group-item-text">@e.description</p>
                            </div>
                            <div class="col-md-3 see-more-btn">
                                <p class="btn btn-primary btn-sm">
                                    See More
                                </p>
                            </div>
                        </div>
                    </a>
                }
            </div>
        </div>
    </div>

    <div class="row">
        <h3>My profile</h3>

        @using (Html.BeginForm("UpdateProfile", "Dashboard", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()
            <div class="form-horizontal">
                @Html.HiddenFor(model => model.user.Id)
                <div class="form-group">
                    @Html.LabelFor(model => model.user.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.user.Email, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.user.Email, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.user.Firstname, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.user.Firstname, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.user.Firstname, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.user.Lastname, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.user.Lastname, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.user.Lastname, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.user.Address, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.user.Address, new { htmlAttributes = new { @class = "form-control", id = "Event_location" } })
                        @Html.ValidationMessageFor(model => model.user.Address, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.Label("Avatar", new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <input class="form-control" type="file" id="Avatar" name="Picture" />
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Update my profile" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }
      </div>
</div>

<script type="text/javascript">
    $(function () {
        var input = document.getElementById('Event_location');
        var options = {
        };

        autocomplete = new google.maps.places.Autocomplete(input, options);
    });


</script>